apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-dev
resources:
- ../../base
- scaledobject.yaml
- servicemonitor.yaml
- networkpolicy.yaml
patches:
- path: patch-env.yaml
images:
- name: ghcr.io/zing-rsa/load-demo-worker
  newTag: 514d1684249dcb532ae140b6153fbd801b14792f
