apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-dev
resources:
  - ../../base
  - scaledobject.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/zing-rsa/load-demo-worker
    newTag: latest # managed by the load-demo deploy workflow
