apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-dev
resources:
- ../../base
- scaledobject.yaml
- servicemonitor.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/zing-rsa/load-demo-worker
  newTag: 0699f54c86fed7b0e74ce1b805d878b85a621213
