apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-dev
resources:
- ../../base
- httproute.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/zing-rsa/lab-web
  newTag: 0700dd5001d9f80ee11f7082c7aae7eda70a9fab
patches:
- patch: |-
    - op: add
      path: /spec/template/metadata/annotations/resource.opentelemetry.io~1deployment.environment.name
      value: dev
  target:
    kind: Deployment
    name: lab-web
