apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-dev
resources:
- ../../base
- httproute.yaml
- servicemonitor.yaml
- networkpolicy.yaml
patches:
- path: patch-env.yaml
images:
- name: ghcr.io/zing-rsa/load-demo-gateway
  newTag: f62662ead4a45badb06287aa9c00549a5d1fbe25
