apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-dev
resources:
- ../../base
- httproute.yaml
- servicemonitor.yaml
- networkpolicy.yaml
patches:
- path: patch-env.yaml
images:
- name: ghcr.io/zing-rsa/load-demo-gateway
  newTag: 3af27834edce83ed625b6e245a8bf4e2ed573b0b
