apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-dev
resources:
- ../../base
- httproute.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/zing-rsa/lab-web
  newTag: 781e19e76441675e4c94b022844ecc2f382e5221
patches:
- patch: |-
    - op: add
      path: /spec/template/metadata/annotations/resource.opentelemetry.io~1deployment.environment.name
      value: dev
  target:
    kind: Deployment
    name: lab-web
