apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-dev
resources:
- ../../base
- httproute.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/zing-rsa/lab-web
  newTag: 343c2e81703d8bac04e20e5d311c28c364d55ea1
patches:
- patch: |-
    - op: add
      path: /spec/template/metadata/annotations/resource.opentelemetry.io~1deployment.environment.name
      value: dev
  target:
    kind: Deployment
    name: lab-web
